#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 28 18:31:25 2021
B07 在B07的基础上，看看猜多少个能够中奖
@author: zhangjun
"""

from B07_Recommend import give_me_guess

def main():
    award ="071522242730"
    count = 0
    times =2
    n = 30
    for j in range(times):
        df = give_me_guess(n)
        if not df.empty:
            for index,row in df.iterrows():
                idnum = row['id']
                r6 = row['r6']
                r5 = row['r5']
                r4 = row['r4']
                r3 = row['r3']
                r2 = row['r2']
                r1 = row['r1']
                string = "{:0>2f}{:0>2f}{:0>2f}{:0>2f}{:0>2f}{:0>2f}".format(r1,r2,r3,r4,r5,r6)
                print(string)
                count += 1
                if award == string:
                    print(idnum,'=======================')
                
    
if __name__ == "__main__":
    main()    